[package]
name = "rotors"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
ciborium = "0.2"
rotors-macros = { path = "../rotors-macros" }
serde = "1"
tonic = { version = "^0.9.2", features = ["codegen", "transport"] }
