[package]
name = "rotors-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
heck = "0.4"
proc-macro2 = "1"
quote = "1"
syn = {version = "2", features= ["extra-traits"]}
